### ISSUE TITLE
Firefox URLs not prefixed with http://ranger.mauve.moe/load-dat-page/?url=

### ISSUE THREAD

**Issue by evdubs** [RangerMauve/load-dat-page#4]
Looking at `http://ranger.mauve.moe/load-dat-page/?url=dat%3A%2F%2F8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748`, I can click on the `option-chain` folder in Chromium and see the contents. 

In Firefox, the URL is set as `dat://8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748/option-chain` with no `http://ranger.mauve.moe/load-dat-page/?url=` prefix. 

When I manually go to `http://ranger.mauve.moe/load-dat-page/?url=dat%3A%2F%2F8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748/option-chain` in Firefox, I can see the contents.

**Comment by RangerMauve** [comment]
Oh! Also make sure you're using the `https://` version of the page

**Comment by RangerMauve** [comment]
The linking seemed to work fine for me on Firefox Nightly

https://ranger.mauve.moe/load-dat-page/?url=dat%3A%2F%2F8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748

**Comment by evdubs** [comment]
You can click on the `option-chain` folder and be shown its contents on Firefox Nightly?

With respect to https:// , when I go to ranger.mauve.moe/load-dat-page, I am sent to the http:// page by default; will you consider having https:// be the default?

**Comment by evdubs** [comment]
Also, here's some interesting behavior:

http://ranger.mauve.moe/load-dat-page/?url=dat%3A%2F%2F8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748/option-chain shows contents for me

https://ranger.mauve.moe/load-dat-page/?url=dat%3A%2F%2F8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748/option-chain just hangs on "Loading..."

The error on https is:

```
Error creating socket to local discovery server DOMException: "The operation is insecure." bundle.js:16864:7
    DiscoverySwarmStreamWebsocket https://ranger.mauve.moe/load-dat-page/bundle.js:16864
    DiscoverySwarmWeb https://ranger.mauve.moe/load-dat-page/bundle.js:16764
    Dat https://ranger.mauve.moe/load-dat-page/bundle.js:14528
    [3]< https://ranger.mauve.moe/load-dat-page/bundle.js:261
    o https://ranger.mauve.moe/load-dat-page/bundle.js:1
    o https://ranger.mauve.moe/load-dat-page/bundle.js:1
    [4]< https://ranger.mauve.moe/load-dat-page/bundle.js:503
    o https://ranger.mauve.moe/load-dat-page/bundle.js:1
    r https://ranger.mauve.moe/load-dat-page/bundle.js:1
    <anonymous> https://ranger.mauve.moe/load-dat-page/bundle.js:1
```

**Comment by RangerMauve** [comment]
The `operation is insecure` issue isn't a problem. It's just attempting to connect to a local gateway that doesn't exit.

**Comment by RangerMauve** [comment]
Both of those links are working for me. :S

Try clearing the storage for the page

**Comment by evdubs** [comment]
https shows contents for me now.

**Comment by evdubs** [comment]
I can confirm that the latest firefox release (not nightly version) does not have this issue.
